### ISSUE TITLE
Request to make _genNoise() available to call from the tools.noise package

### ISSUE THREAD

**Issue by am-thomas** [pysmo/pysmo#89]
Hello, I am currently creating synthetic noise for my research project and want to do so with my own noise models, rather than from Peterson's high and low noise model. I have been using your helper function _gen_Noise() from the tools.noise package by directly copying over its source code to my research repository. It has been working really well! To give proper credit to pysmo and make my code workflow a little less busy, would you be able to make the helper function _genNoise() available through the pysmo package? So, that I would simply need to import the tools.noise package and call the _genNoise() function. Thank you!

**Comment by smlloyd** [comment]
Hi @am-thomas ,

### Short Answer
The function is not exposed via the `__init__.py` file, but should still be importable like this:

`from pysmo.tools.noise.peterson import _genNoise`

or, if you want to get rid of the underscore:

`from pysmo.tools.noise.peterson import _genNoise as genNoise`

### Long Answer
We are currently making quite a few changes going from version 0.8.x (which is presumably what you are using) to version 1.0, We are close to tagging a pre-release, which won't have that much functionality yet, but should otherwise be quite usable (and easy to extend). If you're curious where we are going with pysmo feel free to check out the latest documentation: https://pysmo.readthedocs.io/en/latest/

Please keep in mind that we haven't even made the pre-release yet, so forgive the incomplete and rough state of the documentation.

There will be some changes to the noise functions that may affect your current workflow, but it should be easy for you to fix. As we are in a state of transition, I am happy to make changes to the current tools.noise package to make them more flexible for use cases such as yours. On that note, if you have any noise models (or scripts that generate them) that you think merit inclusion in pysmo itself please do feel free to submit them here!

**Comment by am-thomas** [comment]
Hi @smlloyd, thank you very much! I did not realize the function was importable using pysmo.tools.noise.peterson. Looking forward to the updates of pysmo. My noise models are specific to a station so O don't know if it would be helpful to include at the moment. Will pass along any code or model in the future.
